spring.application.name=HealthRag

# Gemini chat model
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Gemini Embedding Model
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001

# ChromaDB (will run locally via Docker)
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=patient-records
spring.ai.vectorstore.chroma.initialize-schema=true
